### ISSUE TITLE
Error: Command failed: sass-convert --version, with sass is installed in my mac

### ISSUE THREAD

**Issue by dobbbri** [sjova/vscode-sass-format#1]
$ which sass-convert 
/usr/local/bin/sass-convert

$ sass-convert --version                                                                                                  
Sass 3.4.23 (Selective Steve)

console of developer tools error:

[Extension Host] Error: Command failed: which sass-convert 
/usr/local/bin/sass-convert
/bin/sh: sass-convert: command not found

    at checkExecSyncError (child_process.js:502:13)
    at Object.execSync (child_process.js:542:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:685:22)
    at checkDependencies (/Users/sldobri/.vscode/extensions/sasa.vscode-sass-format-1.0.0/out/src/extension.js:17:25)
    at registerSassFormat (/Users/sldobri/.vscode/extensions/sasa.vscode-sass-format-1.0.0/out/src/extension.js:11:5)
    at activate (/Users/sldobri/.vscode/extensions/sasa.vscode-sass-format-1.0.0/out/src/extension.js:7:32)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:373080)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:372865)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:372640
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:62432)

**Comment by sjova** [comment]
Hello sldobri, thanks for reporting this issue. I can't reproduce same error on my side, but let's try to debug this together.

I'm using latest version of macOS: **macOS Sierra 10.12.4 (16E195)**, and latest version of Code: **1.12.1 (1.12.1)**.
For installing *sass command line tools* I followed official procedure from here: [http://sass-lang.com/install](http://sass-lang.com/install) and installed sass tools with this command: `sudo gem install sass`. After this step *sass-convert* command is available globally on my system and can be executed from *macOS Terminal*, same as from *Visual Studio Code Integrated Terminal* and from my extension. In all cases, this is output:

```
$ which node
/Users/myusername/.nvm/versions/node/v6.10.2/bin/node

$ node --version
v6.10.2

$ which gem
/usr/bin/gem

$ gem --version
2.5.1

$ which sass
/usr/local/bin/sass

$ which sass-convert
/usr/local/bin/sass-convert

$ sass --version
Sass 3.4.23 (Selective Steve)

$ sass-convert --version
Sass 3.4.23 (Selective Steve)
```

----

Did you installed ruby and sass via a version manager tool like [RVM](https://rvm.io/), [rbenv](https://github.com/rbenv/rbenv) or something similar?

Did you installed additional shell/terminal environment (ex. `$ brew install zsh`)?

Can you execute following commands from [Visual Studio Code Integrated Terminal](https://code.visualstudio.com/docs/editor/integrated-terminal) and paste me output:

```
$ which node
$ node --version
$ which npm
$ npm --version
$ which gem
$ gem --version
$ which sass
$ which sass-convert
$ sass-convert --version
$ echo test
$ echo $PATH
$ echo $GEM_PATH
$ cat ~/.bash_profile
$ cat ~/.profile
```

Thanks

**Comment by sldobri** [comment]
I use zsh 

 
$ which node  
/usr/local/bin/node
 
$ node --version 
v7.10.0

$ which npm
/usr/local/bin/npm

$  npm --version 
4.2.0

$ which gem
/usr/bin/gem

$ gem --version
2.0.14.1
 
$ which sass 
/usr/local/bin/sass

$ which sass-convert 
/usr/local/bin/sass-convert

$ sass-convert --version
Sass 3.4.23 (Selective Steve)

$ echo test 
test

$ echo $PATH
/usr/local/opt/php71/bin:~/.composer/vendor/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sldobri/.composer/vendor/bin

$ echo $GEM_PATH 


$ cat ~/.bash_profile 
cat: /Users/sldobri/.bash_profile: No such file or directory

$ cat ~/.profile
cat: /Users/sldobri/.profile: No such file or directory

$ cat .zshrc
export ZSH=$HOME/.oh-my-zsh
export NODE_PATH="/usr/local/bin/node"

export PATH="/usr/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="~/.composer/vendor/bin:$PATH"
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
export EDITOR="vim"
export GIT_EDITOR="vim"
export VISUAL="code"

# Zsh Theme
#ZSH_THEME="cloud"
#ZSH_THEME="muse"
ZSH_THEME="sorin"

export LANG=en_US.UTF-8
plugins=(
  npm
  brew
  composer
  laravel5
  git
  git-extras
  bracketsime
  osx
  autocomplete
  syntax-highlighting
  history-substring-search
  theme
  vi-mode
  vi-visual-mode
)

source $ZSH/oh-my-zsh.sh


# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^D" end-of-line
bindkey "^R" history-incremental-search-backward


# shortcuts
alias ..='cd ..'
alias ...='cd ../..'
alias home='cd ~/'
alias icloud='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/'
alias ls='ls -lhaG'
alias lr='ls -lhtr'
alias history='fc -il 1i'
alias c='clear'
alias f='open .'
alias t='trash --force'
alias p='phpunit'
alias rm='rm -ifr'
alias vim='vim'
alias v='mvim'
alias c:versions='rm public/css && rm public/js'

# Pretty print the path
alias path="echo $PATH | tr -s ':' '\n'"


# Atualizar brew
alias bubu="brew update && brew upgrade && brew cleanup"


# diversos
alias bat="pmset -g batt"
alias speed="speed-test"
alias update="sudo softwareupdate -v -i -a"
alias tempo="curl http://wttr.in/pereira_barreto"


# ZSH
alias sz='source ~/.zshrc'
alias zsh='code ~/.zshrc'
alias ohmyzsh="code ~/.oh-my-zsh"
alias zshup="upgrade_oh_my_zsh"


# Git
alias g:aa="git add ."
alias g:s="git status"
alias g:l="git log"
alias g:c="git commit -m"
alias g:p="git push"
alias g:ps="dig a bitbucket.org && git push && git status"
#alias g:ps="ssh-add -K ~/.ssh/id_rsa && ssh -Tv git@bitbucket.org && git push && git status"
alias g:nah='git reset --hard && git clean -df'
alias g:aac='git add . && git commit -m'


# dev
alias ll='cd ~/Code/arturia'
alias gg='ll && g:ps'
# alias ss="m:start && cd ~/Code/arturia/server && reload && art serve"
# alias cc="cd ~/Code/arturia/client && npm run dev"
alias cc="ll && npm run dev"
alias kk="ll && code ."
alias l:reset="php artisan migrate:refresh --seed && php artisan passport:install"

alias bit='dig a bitbucket.org'


# npm
alias n:rd='npm run dev'
alias n:rb='npm run build'


# Laravel
alias t:db="rm database/database.sqlite; touch database/database.sqlite"
alias l:s="php artisan serve"
alias l:rl="php artisan route:list"
alias l:mr="php artisan migrate:refresh"
alias l:mrs="php artisan migrate:refresh --seed"
alias l:t="php artisan tinker"
alias art="php artisan"
alias renew="l:mr; reload"
alias reload='composer dump-autoload;  art view:clear; art cache:clear; art clear-compiled; art config:cache; art route:cache; art optimize'
alias pu="./vendor/bin/phpunit"


# Mysql/MariaDB
alias m:start="mysql.server start"
alias m:s="mysql.server start"
alias m:stop="mysql.server stop"
alias m:restart="mysql.server restart"
alias m:status="mysql.server status"

**Comment by dobbbri** [comment]
- I'm using  macOS Sierra 10.12.5 (16F73), and latest version of Code: 1.12.2 (1.12.2).
- ruby Is what already installed on Mac
- I'm use zsh 

$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
 
$ which node  
/usr/local/bin/node
 
$ node --version 
v7.10.0

$ which npm
/usr/local/bin/npm

$  npm --version 
4.2.0

$ which gem
/usr/bin/gem

$ gem --version
2.0.14.1
 
$ which sass 
/usr/local/bin/sass

$ which sass-convert 
/usr/local/bin/sass-convert

$ sass-convert --version
Sass 3.4.23 (Selective Steve)

$ echo test 
test

$ echo $PATH
/usr/local/opt/php71/bin:~/.composer/vendor/bin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sldobri/.composer/vendor/bin

$ echo $GEM_PATH 


$ cat ~/.bash_profile 
cat: /Users/sldobri/.bash_profile: No such file or directory

$ cat ~/.profile
cat: /Users/sldobri/.profile: No such file or directory

$ cat .zshrc

```
export ZSH=$HOME/.oh-my-zsh
export NODE_PATH="/usr/local/bin/node"

export PATH="/usr/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
export PATH="~/.composer/vendor/bin:$PATH"
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
export EDITOR="vim"
export GIT_EDITOR="vim"
export VISUAL="code"

# Zsh Theme
#ZSH_THEME="cloud"
#ZSH_THEME="muse"
ZSH_THEME="sorin"

export LANG=en_US.UTF-8
plugins=(
  npm
  brew
  composer
  laravel5
  git
  git-extras
  bracketsime
  osx
  autocomplete
  syntax-highlighting
  history-substring-search
  theme
  vi-mode
  vi-visual-mode
)

source $ZSH/oh-my-zsh.sh


# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^D" end-of-line
bindkey "^R" history-incremental-search-backward


# shortcuts
alias ..='cd ..'
alias ...='cd ../..'
alias home='cd ~/'
alias icloud='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs/'
alias ls='ls -lhaG'
alias lr='ls -lhtr'
alias history='fc -il 1i'
alias c='clear'
alias f='open .'
alias t='trash --force'
alias p='phpunit'
alias rm='rm -ifr'
alias vim='vim'
alias v='mvim'
alias c:versions='rm public/css && rm public/js'

# Pretty print the path
alias path="echo $PATH | tr -s ':' '\n'"


# Atualizar brew
alias bubu="brew update && brew upgrade && brew cleanup"


# diversos
alias bat="pmset -g batt"
alias speed="speed-test"
alias update="sudo softwareupdate -v -i -a"
alias tempo="curl http://wttr.in/pereira_barreto"


# ZSH
alias sz='source ~/.zshrc'
alias zsh='code ~/.zshrc'
alias ohmyzsh="code ~/.oh-my-zsh"
alias zshup="upgrade_oh_my_zsh"


# Git
alias g:aa="git add ."
alias g:s="git status"
alias g:l="git log"
alias g:c="git commit -m"
alias g:p="git push"
alias g:ps="dig a bitbucket.org && git push && git status"
#alias g:ps="ssh-add -K ~/.ssh/id_rsa && ssh -Tv git@bitbucket.org && git push && git status"
alias g:nah='git reset --hard && git clean -df'
alias g:aac='git add . && git commit -m'


# dev
alias ll='cd ~/Code/arturia'
alias gg='ll && g:ps'
# alias ss="m:start && cd ~/Code/arturia/server && reload && art serve"
# alias cc="cd ~/Code/arturia/client && npm run dev"
alias cc="ll && npm run dev"
alias kk="ll && code ."
alias l:reset="php artisan migrate:refresh --seed && php artisan passport:install"

alias bit='dig a bitbucket.org'


# npm
alias n:rd='npm run dev'
alias n:rb='npm run build'


# Laravel
alias art="php artisan"
alias l:s="art serve"
alias l:rl="art route:list"
alias l:mr="art migrate:refresh"
alias l:mrs="art migrate:refresh --seed"
alias l:t="php artisan tinker"
alias renew="l:mr && reload"
alias reload='composer dump-autoload &&  art view:clear && art cache:clear && art clear-compiled && art config:cache && art route:cache && art optimize'
alias t:db="rm database/database.sqlite; touch database/database.sqlite"
alias pu="./vendor/bin/phpunit"


# Mysql/MariaDB
alias m:start="mysql.server start"
alias m:s="mysql.server start"
alias m:stop="mysql.server stop"
alias m:restart="mysql.server restart"
alias m:status="mysql.server status"
```

**Comment by dobbbri** [comment]
I install the new version 1.0.1 and is work fine, thanks a lot!!!

**Comment by dobbbri** [comment]
only work if i add the sass-convert path:

const sassConvertCommand = '/usr/local/bin/sass-convert'; // `Sass Formatter` dependency

I tink is because zsh.

Suggestion, create **sassPath** paramater:

"sassFormat.sassPath": "/usr/local/bin" 

value default: null

**Comment by sjova** [comment]
Please update extension to the latest version, set: `"sassFormat.sassPath": "/usr/local/bin"` and let me know if everything works fine. Thanks.

**Comment by dobbbri** [comment]
thanks!!!

**Comment by mehas** [comment]
Thank you. For anyone else having issues, run the command: 

`which sass-convert` 

and copy the portion of your path before `sass-convert` and set it as the value of the `sassFormat.sassPath` variable in your VS Code user settings.

In my case, I installed Ruby with RVM, so my path was:

`/Users/(my user name)/.rvm/gems/ruby-2.4.1/bin/`
