### ISSUE TITLE
Turn off output window

### ISSUE THREAD

**Issue by urre** [sjova/vscode-sass-format#12]
It's a little frustrating when the output windows opens automatically when typing an error, or even when a bracket is not closed while still editing. 

Can i turn that off?

**Comment by sjova** [comment]
@urre Are you using the latest version? There was a similar issue in the previous version when `editor.formatOnPaste` was set on `true`.

If you still have the issue with the latest version, please provide me all details listed here: https://github.com/sjova/vscode-sass-format#issues

Also, paste me whole **User Settings**. Thanks.

**Comment by urre** [comment]
i'm using the latest version 1.1.3. 

Could not find the fix for  `editor.formatOnPaste` you made?

The strange thing is that it validates before i save the document, hence popping up the output tab.

macOS High Sierra 10.13.1
VS Code 1.20.1
ruby 2.4.0p0
Sass 3.5.5 (Bleeding Edge)

**Comment by sjova** [comment]
Also, please paste me your User Settings from VS Code, and I'll double check. Must be related to some additional user settings or VS Code changed something in latest updates.

**Comment by urre** [comment]
No i don't think so, same behavior as before in earlier versions.

**Comment by sjova** [comment]
@urre I can't reproduce this. I tested in a new environment, and everything works fine.

> The strange thing is that it validates before i save the document, hence popping up the output tab.

Some setting and/or some other extension maybe triggering this.

Can you try to remove all custom User Setting from VS Code, and disable all other extensions, just for testing purposes? If this works, try to add back all these one by one?

**Comment by urre** [comment]
Closing this. This seems to be solved. Now the output panel don't show up before i save the document (with the `editor.formatOnPaste` turned on) like it did before.
