### ISSUE TITLE
[Feature] Add option to disable trailing 0

### ISSUE THREAD

**Issue by Nikodermus** [sjova/vscode-sass-format#13]
Usually the trailing 0 in CSS/SCSS is deprecated, it would be nice if users can turn it off with a workspace setting such as `"sassFormat.trailingZero": false`, for example with the current stylelint set I have the trailing 0 is an error and the sass formatter will keep adding it

![scss](https://user-images.githubusercontent.com/7080621/37294764-8b759174-25e4-11e8-8c90-d0821ad11586.gif)

**Comment by sjova** [comment]
Hi, @Nikodermus I'll consider this feature for one of the future updates. Thanks.

**Comment by jakubhomoly** [comment]
Please. This has been bugging me so much. Any ETA on this?

**Comment by sjova** [comment]
@Nikodermus @insanesvk Please update extension and then you can use: `"sassFormat.numberLeadingZero": false`
