### ISSUE TITLE
OptionParser::InvalidOption: invalid option: --quiet

### ISSUE THREAD

**Issue by mclusky** [sjova/vscode-sass-format#14]
HI,

I get this error when I save, and I'm using the sass syntax. Am I missing  something?  Do I need to configure the plugin?

Thanks,
Chris

**Comment by sjova** [comment]
Hi, @Mclusky thanks for the reporting issue.

I can't reproduce the same issue. Can you revisit this notes:

https://github.com/sjova/vscode-sass-format/blob/master/README.md#known-issues
https://github.com/sjova/vscode-sass-format/blob/master/README.md#issues

And paste me some more details?

**Comment by mclusky** [comment]
Hi sjova

Sass 4.0.0.alpha.1 (Bleeding Edge)
/usr/local/bin/sass-convert

I wonder if it's conflicting with another extension. I've disabled scss in beautify though. I did add the path in settings.json 
"sassFormat.sassPath": "/usr/local/bin/sass-convert"
Still, it's not having it.

**Comment by sjova** [comment]
@mclusky Please use **Ruby Sass 3.5.6** from _March 23, 2018_ instead of **4.0.0.alpha.1** from _December 09, 2015_ - this is some old temp version.

More details about versions: https://rubygems.org/gems/sass
