### ISSUE TITLE
grid-template-areas attribute (and others) is not formatted correctly

### ISSUE THREAD

**Issue by PeterGabriel2** [sjova/vscode-sass-format#15]
this is scss:
```
grid-container {
  grid-template-areas: 
    //  1   2          3            4            5       6       7
    'area-a area-img   area-img     area-img'
    'area-a area-text  area-text    area-text'  
    'area-a area-img2  area-img2    area-img2'  
    'area-a area-b     area-boom    area-boom';
}
```
after formatting:
```
  grid-template-areas: 'area-a ar-img  ar-img  ar-img' 'area-a ar-text  ar-text  ar-text'  'area-a ar-img  ar-img  ar-img' 'area-a ar-b  ar-boom  ar-boom';
```
and the comment is deleted!

it would be nice to do NOT format this style of text or even better, format it into columns which every column would keep the same width for better visual recognition.

**Comment by sjova** [comment]
Hi, @PeterGabriel2 thanks for the reporting this issue.

I'll try to extend `sassFormat.inlineComments` setting and/or to introduce the new setting to allow this. Since this is a really specific case I'll mark this as a low priority at this moment.

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
