### ISSUE TITLE
Replacing deprecated sass-convert

### ISSUE THREAD

**Issue by weber-d** [sjova/vscode-sass-format#17]
According to https://github.com/SassDoc/sass-convert/issues/10#issuecomment-378757188 it seems that `sass-convert` is deprecated and should be replaced.

**Comment by sjova** [comment]
Hello @Weber-D, thanks for reporting this.

I'll try to replace Ruby Sass with Dart Sass before June 26, 2018 (3 months from official replacement).

**Comment by sjova** [comment]
`sass-convert` functionality is not yet provided in Dart implementation (more details: [GitHub/Dart Sass/Are you planning to implement sass-convert?](https://github.com/sass/dart-sass/issues/188)). I'll close this issue, and you can follow homepage for more updates about this.

I'll wait few more months, or I'll replace `sass-convert` with some alternative (node-sass, Sass.js).
