### ISSUE TITLE
.wxss file format error

### ISSUE THREAD

**Issue by zhanxiaoge** [sjova/vscode-sass-format#19]
before

![1](https://user-images.githubusercontent.com/19665552/39391197-50e305a6-4ad2-11e8-87c4-194150868cc4.png)

Shift+Alt+F

after

![2](https://user-images.githubusercontent.com/19665552/39391201-7c470706-4ad2-11e8-869a-9599cce82aff.png)

**Comment by sjova** [comment]
hi @nailao `.wxss` format is not supported at this moment
