### ISSUE TITLE
something goes wrong when I set "editor.formatOnSave": true

### ISSUE THREAD

**Issue by jeeeez** [sjova/vscode-sass-format#2]
If I set `"editor.formatOnSave": true` in VS Code, when I save my .sass file after modify, `vscode-sass-format` plugin will reset my file before excute sass-format.

**Comment by sjova** [comment]
Hello PickerLee, thanks for reporting this issue. Please update extension to the latest version and let me know if everything works as expected. Thanks.

**Comment by jeeeez** [comment]
It works! thx

**Comment by sjova** [comment]
Thanks.
