### ISSUE TITLE
Support node-sass

### ISSUE THREAD

**Issue by MadaraUchiha** [sjova/vscode-sass-format#21]
I've seen #18, and there hasn't seem to be advancement since then (I still get the `sass-convert` not found error)

What would it take to move to node-sass, which is more likely to be installed alongside a JavaScript editor like VSCode?

I'm willing to put out a PR if it isn't too huge of an endeavour ;)

**Comment by ChariseWalraven** [comment]
I would like to add to this that [ruby-sass is now deprecated](https://sass-lang.com/ruby-sass).

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
