### ISSUE TITLE
Issue with using single quotes

### ISSUE THREAD

**Issue by gethinoakes** [sjova/vscode-sass-format#22]
There seems to be an issue when using single quotes and inserting a URL, it leave the first single quote alone but changes the last to a double quote, results in errors.

e.g.
`@import url('https://fonts.googleapis.com/css?family=Open+Sans');`

gets changed to
`@import url('https://fonts.googleapis.com/css?family=Open+Sans");`

macOS 10.14
VSCode 1.27.2
Sass Formatter 1.1.6

Other extensions I have installed for sass are SCSS IntelliSense and stylelint. I have tried disabling these, but it is only when I disable the Sass Formatter plugin that it stops doing this.

Thanks in advance.

**Comment by AlbanBujupaj** [comment]
Same issue.

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
