### ISSUE TITLE
Leading zero option (`"sassFormat.numberLeadingZero": false`), correcting to the final digit

### ISSUE THREAD

**Issue by ghostPepperWonton** [sjova/vscode-sass-format#23]
Issue Type: <b>Bug</b>

For some reason, whenever I correct something that is less than 1, it gets corrected to the final digit rather than the original decimal without the zero.

Examples:
```
| Before   | After | Should be |
| -------- | ----- | --------- |
| 0.125rem | .5rem | .125rem   |
| 0.33rem  | .3rem | .33rem    |
| .66rem   | .6rem | .66rem    |
| 0.8em    | .8em  | .8em      |
| 1.4px    | 1.4px | 1.4px     |
```

**My information:**

- OS: macOS Mojave 10.14 (Darwin x64 18.0.0)
- VS Code version: 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:18:43.347Z)
- Sass Formatter version: 1.1.6
- `sass-convert` version: Sass 3.6.0
- Console errors: none

<details>
<summary>Extensions installed:</summary>

- Better Haml
- Color Highlight
- Docker
- DotENV
- ElixirLinter
- ESLint*
- Fold Plus
- GitLens
- GraphQL
- Haml Lint
- HTMLHint
- Import Cost
- Jest
- Lorem ipsum
- Markdown HTML
- Material Icon Theme
- Monokai Seti
- npm Intellisense
- One Dark Pro
- Prettier - Code formatter*
- px to rem
- Rainbow CSV
- Rewrap
- Ruby
- Ruby Solargraph
- ruby-rubocop
- rufo (Ruby formatter)
- Sass*
- Sass Formatter
- Sass Lint*
- Settings Sync
- VS Color Picker
- vscode-elixir
- vscode-icons
- vscode-styled-components
- Word Count

*- These are the extensions I've tested disabling to no effect.

</details>
<br />
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
