### ISSUE TITLE
new line after selector lists - 

### ISSUE THREAD

**Issue by orionrush** [sjova/vscode-sass-format#24]
When I create resets and the like, I normally will not put each selector on a new line to conserve space like so:

```
html, body,
h1, h2, h3, h4,h5, h6,
a, p, span, em, small, strong, (and so on) 
{
	display: block;
}
```

Is there a way to create an exception for the auto line-return formatting in these cases?

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
