### ISSUE TITLE
Respecting brace-style setting in sass-lint

### ISSUE THREAD

**Issue by nukithelegend** [sjova/vscode-sass-format#25]
Please consider adding support for respecting the brace-style setting in sass-lint (I am specifically having issues with the placement of the else clause when auto-formatting).

Current behavior:
```sass
@mixin should-hover($excluded-selector: "") {
	@if $excluded-selector != "" {
		@at-root body.should-hover &:hover:not(#{$excluded-selector}),
		&:focus {
			@content;
		}
	}
	@else {
		@at-root body.should-hover &:hover,
		&:focus {
			@content;
		}
	}
}
```

Expected behaviour:
```sass
@mixin should-hover($excluded-selector: "") {
	@if $excluded-selector != "" {
		@at-root body.should-hover &:hover:not(#{$excluded-selector}),
		&:focus {
			@content;
		}
	} @else {
		@at-root body.should-hover &:hover,
		&:focus {
			@content;
		}
	}
}
```

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
