### ISSUE TITLE
'sass-convert' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rritoch** [sjova/vscode-sass-format#26]
The installation instructions link say you must run `npm install -g sass` but that doesn't install sass-convert.

**Comment by celsomtrindade** [comment]
Same here. I've heard that it's deprecated, but this project is still using {?}.

**Comment by ghost** [comment]
Years later, still running into this.

**Comment by sjova** [comment]
Follow instruction for installing old Ruby Sass (`gem install sass`), instead of new Dart Sass (`npm install -g sass`)

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
