### ISSUE TITLE
useSingleQuotes replaces double quotes in KSS documentation(commented section)

### ISSUE THREAD

**Issue by saxena-ashutosh** [sjova/vscode-sass-format#3]
useSingleQuotes rule will format double quote from commented text . We are using KSS documentation in which we have defined our markup in scss files and this rule replace all double quote from commented markup. e.g.
before running formatter:
/* <ex-input-form labelText= "this doesn't format" */

after running formatter:
/* <ex-input-form labelText= 'this doesn't format'></ex-input-form> */
which leads error while rendering KSS documentaion.
please help on this.

**Comment by sjova** [comment]
Sorry for the delay in replying, I was on vacaton. I'll try to fix this tomorrow.

**Comment by sjova** [comment]
I updated extension and if you're using `useSingleQuotes` setting now, double quotes in comments will remain untouched. I tested multiple different cases (default CSS comments - single line/multi line, Sass comments, inline comments) and everything works fine.

For testing purposes I used examples from here with double quotes inside of comments:
https://developer.mozilla.org/en-US/docs/Web/CSS/Comments
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Comments________and_____comments
http://warpspire.com/kss/syntax/

Please update extension to the latest version on your side and let me know if everything is good. Thanks.

**Comment by sjova** [comment]
I'll consider this as done. If there is any additional issue on your side, feel free to reopen this issue or create new one. Thanks.

**Comment by saxena-ashutosh** [comment]
Hi Sasa,

Sorry for the delay, today I have tried same issue with latest version and found it working fine for us. Thanks for help.

**Comment by saxena-ashutosh** [comment]
Hi Sasa,

I also have one observation regarding sass formatter i.e. formatter is not splitting &.abc, &.def into below given format:

&.abc,
&.def {
//sample code
}

Please look if you can help us in this.

**Comment by sjova** [comment]
Hi saxena-ashutosh,

Thanks for checking. I'm glad to help you.

About 2nd topic, that is how `sass-convert` console tool work. For those cases formatter will fix only spacing and indention, in this way formatter will not break user coding style. Someone and/or some css frameworks like to put all selectors in single line, and others like to put each selector in new line. I can't do anything around this.

Best
