### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by johnRambo2k14** [sjova/vscode-sass-format#4]
Hi,

I think this extension is great and I'm really appreciative for the effort you have put in!

I have some suggestions which could make this extension better:

Add a sass-lint integration, this would be really useful when auto-formating your code, it would read the .sass-lint.yml file in the root of your project and would use settings from there.

I would recommend adding an option to remove the '0' in decimal values that are below the integer of 1. For example, 

instead of 

`transform: scale(0.6);`

it would be

`transform: scale(.6);`

These are just my suggestions anyway, really liking this extension, thanks!

**Comment by sjova** [comment]
Thank you very much for your kind words. I was added Sass Lint configuration support in features roadmad, and I'll work on this when I get more free time. Thank you for your suggestion.

**Comment by CKGrafico** [comment]
Sass lint support could be a WIN

**Comment by sjova** [comment]
I'm no longer maintain this extension. You can find more details in the project [README](https://github.com/sjova/vscode-sass-format#important). So I'll close this issue.
