### ISSUE TITLE
CSS files gets formated as SCSS

### ISSUE THREAD

**Issue by orlandovallejos** [sjova/vscode-sass-format#5]
The description of this tool says "Beautify sass, scss and css files." but when I try to format a CSS file I get the wrong format:

Take a look to this gif:
[https://cl.ly/3s3s2H1K152o](https://cl.ly/3s3s2H1K152o)

**Comment by sjova** [comment]
Please update extension to the latest version and let me know if everything works fine. Thanks.

**Comment by orlandovallejos** [comment]
Works perfect!
Awesome extension by the way!

**Comment by sjova** [comment]
Thanks.
