### ISSUE TITLE
Format on Save?

### ISSUE THREAD

**Issue by andrewmartin** [sjova/vscode-sass-format#6]
This might be a question for how to set up Vscode more so than this extension, but I've had an annoying thing where the sass formatter interrupts my workflow while I'm typing. I'd love to only have it run on `save` instead of `keyup`. How to do this?

**Comment by sjova** [comment]
Please provide me following details:
* Operating system version
* VS Code version
* User and workspace settings (see below)

And I'll try to reproduce issue you described above.

To copy/paste your user and workspace settings use the menu command **File > Preferences > Settings** (**Code > Preferences > Settings on Mac**).

**Comment by sjova** [comment]
I'll close the issue due to inactivity, but feel free to re-open if needed.
